name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: '8.12.1'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Add tsc matcher
      run: echo "::add-matcher::.github/matchers/tsc.json"
    - name: Type check
      run: pnpm typecheck
    - name: Remove tsc matcher
      run: echo "::remove-matcher owner=tsc::"
    - name: Run tests
      run: pnpm test
    - name: Add ESLint matcher
      run: echo "::add-matcher::.github/matchers/eslint-stylish.json"
    - name: Check lint
      run: pnpm lint
    - name: Remove ESLint matcher
      run: echo "::remove-matcher owner=eslint-stylish::"

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: '8.12.1'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build
      run: pnpm build

