name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install TypeScript dependencies
      run: |
        cd typescript
        npm ci

    - name: Run TypeScript tests
      run: |
        cd typescript
        npm test

    - name: Install Python dependencies
      run: |
        cd python
        pip install -r requirements.txt

    - name: Run Python tests
      run: |
        cd python
        pytest -v

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: |
          typescript/coverage/coverage-final.json
          python/coverage.xml
        fail_ci_if_error: true 